services:
  - type: web
    name: dzmarket-pro
    plan: free
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_DEFAULT_ENGINES_NODE
        value: ">=16.0.0"
      - key: PORT
        value: "3000"
    autoDeploy: true
    maxInstances: 3
